<?php

/**
 * @file
 * Register Multiple - enables a user to register for multiple events
 */

/** 
 * This hook adds an Availability option to any operation (e.g. Edit, View etc..) for a user  
 */
function register_multiple_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
    $operations = array();
    
    if ($entity instanceof \Drupal\user\Entity\User) {
        $user = $entity->get('uid')->value;
        $operations['availability'] = array(
            'title' => t('Availability'),
            'url' => \Drupal\Core\Url::fromRoute('register_multiple.registration_form', array('user' => $user)),
            'weight' => 50,
        );
    }
    return $operations;
}
